///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class addCustomerModelData {
/*
{
  "nama": "Romo",
  "umur": "20",
  "gender": "laki laki",
  "alamat": "Jember",
  "tanggal_lahir": "01 09 2000",
  "status": "silver",
  "store_id": 2,
  "updated_at": "2023-11-08T08:10:45.000000Z",
  "created_at": "2023-11-08T08:10:45.000000Z",
  "id": 6
} 
*/

  String? nama;
  String? umur;
  String? gender;
  String? alamat;
  String? tanggalLahir;
  String? status;
  int? storeId;
  String? updatedAt;
  String? createdAt;
  int? id;

  addCustomerModelData({
    this.nama,
    this.umur,
    this.gender,
    this.alamat,
    this.tanggalLahir,
    this.status,
    this.storeId,
    this.updatedAt,
    this.createdAt,
    this.id,
  });
  addCustomerModelData.fromJson(Map<String, dynamic> json) {
    nama = json['nama']?.toString();
    umur = json['umur']?.toString();
    gender = json['gender']?.toString();
    alamat = json['alamat']?.toString();
    tanggalLahir = json['tanggal_lahir']?.toString();
    status = json['status']?.toString();
    storeId = json['store_id']?.toInt();
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['nama'] = nama;
    data['umur'] = umur;
    data['gender'] = gender;
    data['alamat'] = alamat;
    data['tanggal_lahir'] = tanggalLahir;
    data['status'] = status;
    data['store_id'] = storeId;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    data['id'] = id;
    return data;
  }
}

class addCustomerModel {
/*
{
  "success": true,
  "data": {
    "nama": "Romo",
    "umur": "20",
    "gender": "laki laki",
    "alamat": "Jember",
    "tanggal_lahir": "01 09 2000",
    "status": "silver",
    "store_id": 2,
    "updated_at": "2023-11-08T08:10:45.000000Z",
    "created_at": "2023-11-08T08:10:45.000000Z",
    "id": 6
  },
  "message": "Products retrieved successfully."
} 
*/

  bool? success;
  addCustomerModelData? data;
  String? message;

  addCustomerModel({
    this.success,
    this.data,
    this.message,
  });
  addCustomerModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null)
        ? addCustomerModelData.fromJson(json['data'])
        : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
