///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CustomerModelData {
/*
{
  "id": 11,
  "nama": "Romo",
  "umur": "20",
  "gender": "laki laki",
  "alamat": "Jember",
  "tanggal_lahir": "01 09 2000",
  "status": "silver",
  "store_id": 5,
  "created_at": "2023-11-15T04:17:03.000000Z",
  "updated_at": "2023-11-15T04:17:03.000000Z"
} 
*/

  int? id;
  String? nama;
  String? umur;
  String? gender;
  String? alamat;
  String? tanggal_lahir;
  String? status;
  int? store_id;
  String? created_at;
  String? updated_at;

  CustomerModelData({
    this.id,
    this.nama,
    this.umur,
    this.gender,
    this.alamat,
    this.tanggal_lahir,
    this.status,
    this.store_id,
    this.created_at,
    this.updated_at,
  });
  CustomerModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    nama = json['nama']?.toString();
    umur = json['umur']?.toString();
    gender = json['gender']?.toString();
    alamat = json['alamat']?.toString();
    tanggal_lahir = json['tanggal_lahir']?.toString();
    status = json['status']?.toString();
    store_id = json['store_id']?.toInt();
    created_at = json['created_at']?.toString();
    updated_at = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['nama'] = nama;
    data['umur'] = umur;
    data['gender'] = gender;
    data['alamat'] = alamat;
    data['tanggal_lahir'] = tanggal_lahir;
    data['status'] = status;
    data['store_id'] = store_id;
    data['created_at'] = created_at;
    data['updated_at'] = updated_at;
    return data;
  }
}

class CustomerModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 11,
      "nama": "Romo",
      "umur": "20",
      "gender": "laki laki",
      "alamat": "Jember",
      "tanggal_lahir": "01 09 2000",
      "status": "silver",
      "store_id": 5,
      "created_at": "2023-11-15T04:17:03.000000Z",
      "updated_at": "2023-11-15T04:17:03.000000Z"
    }
  ],
  "message": "Products retrieved successfully."
} 
*/

  bool? success;
  List<CustomerModelData?>? data;
  String? message;

  CustomerModel({
    this.success,
    this.data,
    this.message,
  });
  CustomerModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <CustomerModelData>[];
      v.forEach((v) {
        arr0.add(CustomerModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
