///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AuthData {
/*
{
  "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTAxYTgzOTIwMTY1MjRjMDE0MzI0ZDk1YjEyYzJkZDM5MGQ4MGJjZGFhNTEzMDM1ZmE5NGNiZjYyYzM2NjY5MGE2ZmJjZDUzMzJkM2Y3ODkiLCJpYXQiOjE2OTg2NDA3ODAuODU5OTM1LCJuYmYiOjE2OTg2NDA3ODAuODU5OTM3LCJleHAiOjE3MzAyNjMxODAuODUwNDIzLCJzdWIiOiI3Iiwic2NvcGVzIjpbXX0.cxnFLNTfq2uB566lTD1WnLdD8NOtQKntNBARo6VupQVMUPj8SULAzN8F-OhDL-s7F0QAgECkyaV6jeseG3Hg8oz_solUv5u9hMqfJX5Wyruoz6wR6DFJmC54av7FvB76J1CA9aLk-VPzCTnPqFUiKOMJ1XtDsOJtUkMDUQYvlmPQIFKW05pui33Mmvvsyk3TXHdMIv7gcLIehgCbAtW9LH1oMKIGbjbXmYSKaDhrsrRuUttVY-UAnl6jwZ0GssduMutsviq66Og_APUvTtvbW20KvCiIT_AbEmewLWMT6FZPMY08VyGsgd0lHa4vbT4AOIO_f1Gw72571kHQ08XB8uSOI8PK3OyVVxFkwW-3O-JIK4QZBdlCDVK1clMe5dtuh4-KcN7z38k7GqTLSTv20ZZoSTTMsXO1qc3xLxOXfTG0yFFFrkeB623ym-Dp7aN5O1JdjD3EBRQ51IuKWnchnIJeIIEa7kRLNMCisbqAJsn0S4SJRrmNpLyUXN9u3vBc8fP8Ij6Wi8j1Ux0lhhBJsrHPYldscw2YSnOOVKWN4AI4D1FH4ln0b1AhtZ9TuAGhHIja8H8AK_He4gTLMPo9UpOYKBiyq5m0YSfL7DGznA-uz-vIK59AnJvmu4kNEbg5R3IBAJPUcsRLpnzVCtn0c1UTElOPaTJOhrn8dwnIR0Q",
  "name": "admin"
} 
*/

  String? token;
  String? name;

  AuthData({
    this.token,
    this.name,
  });
  AuthData.fromJson(Map<String, dynamic> json) {
    token = json['token']?.toString();
    name = json['name']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['token'] = token;
    data['name'] = name;
    return data;
  }
}

class Auth {
/*
{
  "success": true,
  "data": {
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiOTAxYTgzOTIwMTY1MjRjMDE0MzI0ZDk1YjEyYzJkZDM5MGQ4MGJjZGFhNTEzMDM1ZmE5NGNiZjYyYzM2NjY5MGE2ZmJjZDUzMzJkM2Y3ODkiLCJpYXQiOjE2OTg2NDA3ODAuODU5OTM1LCJuYmYiOjE2OTg2NDA3ODAuODU5OTM3LCJleHAiOjE3MzAyNjMxODAuODUwNDIzLCJzdWIiOiI3Iiwic2NvcGVzIjpbXX0.cxnFLNTfq2uB566lTD1WnLdD8NOtQKntNBARo6VupQVMUPj8SULAzN8F-OhDL-s7F0QAgECkyaV6jeseG3Hg8oz_solUv5u9hMqfJX5Wyruoz6wR6DFJmC54av7FvB76J1CA9aLk-VPzCTnPqFUiKOMJ1XtDsOJtUkMDUQYvlmPQIFKW05pui33Mmvvsyk3TXHdMIv7gcLIehgCbAtW9LH1oMKIGbjbXmYSKaDhrsrRuUttVY-UAnl6jwZ0GssduMutsviq66Og_APUvTtvbW20KvCiIT_AbEmewLWMT6FZPMY08VyGsgd0lHa4vbT4AOIO_f1Gw72571kHQ08XB8uSOI8PK3OyVVxFkwW-3O-JIK4QZBdlCDVK1clMe5dtuh4-KcN7z38k7GqTLSTv20ZZoSTTMsXO1qc3xLxOXfTG0yFFFrkeB623ym-Dp7aN5O1JdjD3EBRQ51IuKWnchnIJeIIEa7kRLNMCisbqAJsn0S4SJRrmNpLyUXN9u3vBc8fP8Ij6Wi8j1Ux0lhhBJsrHPYldscw2YSnOOVKWN4AI4D1FH4ln0b1AhtZ9TuAGhHIja8H8AK_He4gTLMPo9UpOYKBiyq5m0YSfL7DGznA-uz-vIK59AnJvmu4kNEbg5R3IBAJPUcsRLpnzVCtn0c1UTElOPaTJOhrn8dwnIR0Q",
    "name": "admin"
  },
  "message": "User register successfully."
} 
*/

  bool? success;
  AuthData? data;
  String? message;

  Auth({
    this.success,
    this.data,
    this.message,
  });
  Auth.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? AuthData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
