///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CartModelData {
/*
{
  "id": 8,
  "user_id": 6,
  "nama": "Nike Air Jordan",
  "gambar": "IMG-20231105-WA0016.jpg",
  "harga": 2500000,
  "id_product": 61,
  "qty": 1,
  "ukuransepatu": 37,
  "store_id": 2,
  "created_at": "2023-11-06T07:38:52.000000Z",
  "updated_at": "2023-11-06T07:38:52.000000Z"
} 
*/

  int? id;
  int? user_id;
  String? nama;
  String? gambar;
  int? harga;
  int? id_product;
  int? qty;
  int? ukuransepatu;
  int? store_id;
  String? created_at;
  String? updated_at;

  CartModelData({
    this.id,
    this.user_id,
    this.nama,
    this.gambar,
    this.harga,
    this.id_product,
    this.qty,
    this.ukuransepatu,
    this.store_id,
    this.created_at,
    this.updated_at,
  });
  CartModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    user_id = json['user_id']?.toInt();
    nama = json['nama']?.toString();
    gambar = json['gambar']?.toString();
    harga = json['harga']?.toInt();
    id_product = json['id_product']?.toInt();
    qty = json['qty']?.toInt();
    ukuransepatu = json['ukuransepatu']?.toInt();
    store_id = json['store_id']?.toInt();
    created_at = json['created_at']?.toString();
    updated_at = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['user_id'] = user_id;
    data['nama'] = nama;
    data['gambar'] = gambar;
    data['harga'] = harga;
    data['id_product'] = id_product;
    data['qty'] = qty;
    data['ukuransepatu'] = ukuransepatu;
    data['store_id'] = store_id;
    data['created_at'] = created_at;
    data['updated_at'] = updated_at;
    return data;
  }
}

class CartModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 61,
      "nama_product": "Nike Air Jordan",
      "gambar": "IMG-20231105-WA0016.jpg",
      "harga": 2500000,
      "stock": 60,
      "size": [
        {
          "id": 158,
          "id_product": "61",
          "size": "37",
          "stok": "20",
          "status": "tersedia",
          "created_at": "2023-11-06T06:41:59.000000Z",
          "updated_at": "2023-11-06T06:41:59.000000Z",
          "store_id": 2
        }
      ]
    }
  ],
  "message": "Products retrieved successfully."
} 
*/

  bool? success;
  List<CartModelData?>? data;
  String? message;

  CartModel({
    this.success,
    this.data,
    this.message,
  });
  CartModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <CartModelData>[];
      v.forEach((v) {
        arr0.add(CartModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
