///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CheckoutModelData {
/*
{
  "user_id": 6,
  "store_id": "5",
  "name_customer": "Romo",
  "total": 2000000,
  "qty": 1,
  "updated_at": "2023-11-15T06:39:15.000000Z",
  "created_at": "2023-11-15T06:39:15.000000Z",
  "id": 59
} 
*/

  int? user_id;
  String? store_id;
  String? name_customer;
  int? total;
  int? qty;
  String? updated_at;
  String? created_at;
  int? id;

  CheckoutModelData({
    this.user_id,
    this.store_id,
    this.name_customer,
    this.total,
    this.qty,
    this.updated_at,
    this.created_at,
    this.id,
  });
  CheckoutModelData.fromJson(Map<String, dynamic> json) {
    user_id = json['user_id']?.toInt();
    store_id = json['store_id']?.toString();
    name_customer = json['name_customer']?.toString();
    total = json['total']?.toInt();
    qty = json['qty']?.toInt();
    updated_at = json['updated_at']?.toString();
    created_at = json['created_at']?.toString();
    id = json['id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = user_id;
    data['store_id'] = store_id;
    data['name_customer'] = name_customer;
    data['total'] = total;
    data['qty'] = qty;
    data['updated_at'] = updated_at;
    data['created_at'] = created_at;
    data['id'] = id;
    return data;
  }
}

class CheckoutModel {
/*
{
  "success": true,
  "data": [
    {
      "user_id": 6,
      "store_id": "5",
      "name_customer": "Romo",
      "total": 2000000,
      "qty": 1,
      "updated_at": "2023-11-15T06:39:15.000000Z",
      "created_at": "2023-11-15T06:39:15.000000Z",
      "id": 59
    }
  ],
  "message": "Products retrieved successfully."
} 
*/

  bool? success;
  List<CheckoutModelData?>? data;
  String? message;

  CheckoutModel({
    this.success,
    this.data,
    this.message,
  });
  CheckoutModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <CheckoutModelData>[];
      v.forEach((v) {
        arr0.add(CheckoutModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
