/**
 *
 * Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
 *
 */
class ProductModelDataSize {
/*
{
  "id": 158,
  "id_product": "61",
  "size": "37",
  "stok": "20",
  "status": "tersedia",
  "created_at": "2023-11-06T06:41:59.000000Z",
  "updated_at": "2023-11-06T06:41:59.000000Z",
  "store_id": 2
} 
*/

  int? id;
  String? id_product;
  String? size;
  String? stok;
  int? price;
  String? status;
  String? created_at;
  String? updated_at;
  int? store_id;

  ProductModelDataSize({
    this.id,
    this.id_product,
    this.size,
    this.stok,
    this.price,
    this.status,
    this.created_at,
    this.updated_at,
    this.store_id,
  });
  ProductModelDataSize.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    id_product = json['id_product']?.toString();
    size = json['size']?.toString();
    stok = json['stok']?.toString();
    price = json['price']?.toInt();
    status = json['status']?.toString();
    created_at = json['created_at']?.toString();
    updated_at = json['updated_at']?.toString();
    store_id = json['store_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['id_product'] = id_product;
    data['size'] = size;
    data['stok'] = stok;
    data['price'] = price;
    data['status'] = status;
    data['created_at'] = created_at;
    data['updated_at'] = updated_at;
    data['store_id'] = store_id;
    return data;
  }
}

class ProductModelData {
/*
{
  "id": 61,
  "nama_product": "Nike Air Jordan",
  "gambar": "IMG-20231105-WA0016.jpg",
  "harga": 2500000,
  "stock": 60,
  "size": [
    {
      "id": 158,
      "id_product": "61",
      "size": "37",
      "stok": "20",
      "status": "tersedia",
      "created_at": "2023-11-06T06:41:59.000000Z",
      "updated_at": "2023-11-06T06:41:59.000000Z",
      "store_id": 2
    }
  ]
} 
*/

  int? id;
  String? nama_product;
  String? gambar;
  int? harga;
  int? stock;
  List<ProductModelDataSize?>? size;

  ProductModelData({
    this.id,
    this.nama_product,
    this.gambar,
    this.harga,
    this.stock,
    this.size,
  });
  ProductModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    nama_product = json['nama_product']?.toString();
    gambar = json['gambar']?.toString();
    harga = json['harga']?.toInt();
    stock = json['stock']?.toInt();
    if (json['size'] != null) {
      final v = json['size'];
      final arr0 = <ProductModelDataSize>[];
      v.forEach((v) {
        arr0.add(ProductModelDataSize.fromJson(v));
      });
      size = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['nama_product'] = nama_product;
    data['gambar'] = gambar;
    data['harga'] = harga;
    data['stock'] = stock;
    if (size != null) {
      final v = size;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['size'] = arr0;
    }
    return data;
  }
}

class ProductModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 61,
      "nama_product": "Nike Air Jordan",
      "gambar": "IMG-20231105-WA0016.jpg",
      "harga": 2500000,
      "stock": 60,
      "size": [
        {
          "id": 158,
          "id_product": "61",
          "size": "37",
          "stok": "20",
          "status": "tersedia",
          "created_at": "2023-11-06T06:41:59.000000Z",
          "updated_at": "2023-11-06T06:41:59.000000Z",
          "store_id": 2
        }
      ]
    }
  ],
  "message": "Products retrieved successfully."
} 
*/

  bool? success;
  List<ProductModelData?>? data;
  String? message;

  ProductModel({
    this.success,
    this.data,
    this.message,
  });
  ProductModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ProductModelData>[];
      v.forEach((v) {
        arr0.add(ProductModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
