///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BelumLunasModelData {
/*
{
  "user_id": 6,
  "order_id": 56,
  "product_id": 69,
  "store_id": 5,
  "size": 37,
  "harga": 2500000,
  "status": "belum lunas",
  "name_customer": "Romo",
  "tanggal_pemesanan": "2023-11-05 00:00:00",
  "qty": 1,
  "nama_product": "Adidas New Version",
  "gambar": "01-ADIDAS-FFSSBADI5-ADIEG4958-Multicolor.jpg",
  "merk": null
} 
*/

  int? userId;
  int? orderId;
  int? productId;
  int? storeId;
  int? size;
  int? harga;
  String? status;
  String? nameCustomer;
  String? tanggalPemesanan;
  int? qty;
  String? namaProduct;
  String? gambar;
  String? merk;

  BelumLunasModelData({
    this.userId,
    this.orderId,
    this.productId,
    this.storeId,
    this.size,
    this.harga,
    this.status,
    this.nameCustomer,
    this.tanggalPemesanan,
    this.qty,
    this.namaProduct,
    this.gambar,
    this.merk,
  });
  BelumLunasModelData.fromJson(Map<String, dynamic> json) {
    userId = json['user_id']?.toInt();
    orderId = json['order_id']?.toInt();
    productId = json['product_id']?.toInt();
    storeId = json['store_id']?.toInt();
    size = json['size']?.toInt();
    harga = json['harga']?.toInt();
    status = json['status']?.toString();
    nameCustomer = json['name_customer']?.toString();
    tanggalPemesanan = json['tanggal_pemesanan']?.toString();
    qty = json['qty']?.toInt();
    namaProduct = json['nama_product']?.toString();
    gambar = json['gambar']?.toString();
    merk = json['merk']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['user_id'] = userId;
    data['order_id'] = orderId;
    data['product_id'] = productId;
    data['store_id'] = storeId;
    data['size'] = size;
    data['harga'] = harga;
    data['status'] = status;
    data['name_customer'] = nameCustomer;
    data['tanggal_pemesanan'] = tanggalPemesanan;
    data['qty'] = qty;
    data['nama_product'] = namaProduct;
    data['gambar'] = gambar;
    data['merk'] = merk;
    return data;
  }
}

class BelumLunasModel {
/*
{
  "success": true,
  "data": [
    {
      "user_id": 6,
      "order_id": 56,
      "product_id": 69,
      "store_id": 5,
      "size": 37,
      "harga": 2500000,
      "status": "belum lunas",
      "name_customer": "Romo",
      "tanggal_pemesanan": "2023-11-05 00:00:00",
      "qty": 1,
      "nama_product": "Adidas New Version",
      "gambar": "01-ADIDAS-FFSSBADI5-ADIEG4958-Multicolor.jpg",
      "merk": null
    }
  ],
  "message": "Products retrieved successfully."
} 
*/

  bool? success;
  List<BelumLunasModelData?>? data;
  String? message;

  BelumLunasModel({
    this.success,
    this.data,
    this.message,
  });
  BelumLunasModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <BelumLunasModelData>[];
      v.forEach((v) {
        arr0.add(BelumLunasModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
