///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ProfilData {
/*
{
  "id": 6,
  "name": "admin11",
  "email": "admin11@gmail.com",
  "email_verified_at": null,
  "created_at": "2023-10-30T04:33:15.000000Z",
  "updated_at": "2023-10-31T07:03:10.000000Z",
  "is_superadmin": "admin",
  "store_id": null
} 
*/

  int? id;
  String? name;
  String? email;
  String? emailVerifiedAt;
  String? createdAt;
  String? updatedAt;
  String? isSuperadmin;
  String? storeId;

  ProfilData({
    this.id,
    this.name,
    this.email,
    this.emailVerifiedAt,
    this.createdAt,
    this.updatedAt,
    this.isSuperadmin,
    this.storeId,
  });
  ProfilData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    email = json['email']?.toString();
    emailVerifiedAt = json['email_verified_at']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    isSuperadmin = json['is_superadmin']?.toString();
    storeId = json['store_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['email_verified_at'] = emailVerifiedAt;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    data['is_superadmin'] = isSuperadmin;
    data['store_id'] = storeId;
    return data;
  }
}

class Profil {
/*
{
  "success": true,
  "data": {
    "id": 6,
    "name": "admin11",
    "email": "admin11@gmail.com",
    "email_verified_at": null,
    "created_at": "2023-10-30T04:33:15.000000Z",
    "updated_at": "2023-10-31T07:03:10.000000Z",
    "is_superadmin": "admin",
    "store_id": null
  },
  "message": "Products retrieved successfully."
} 
*/

  bool? success;
  ProfilData? data;
  String? message;

  Profil({
    this.success,
    this.data,
    this.message,
  });
  Profil.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    data = (json['data'] != null) ? ProfilData.fromJson(json['data']) : null;
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    data['message'] = message;
    return data;
  }
}
