///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class RestockData {
/*
{
  "id": 9,
  "nama_product": "Adidas New Version",
  "id_product": 69,
  "store_id": 5,
  "purchase_id": 12,
  "size": "40",
  "qty": 30,
  "harga": 2500000,
  "status": "dikirim",
  "tanggal_pemesanan": "11-10-2023",
  "created_at": "2023-11-10T09:50:41.000000Z",
  "updated_at": "2023-11-10T09:50:41.000000Z"
} 
*/

  int? id;
  String? nama_product;
  int? id_product;
  int? store_id;
  int? purchase_id;
  String? size;
  int? qty;
  int? harga;
  String? status;
  String? tanggal_pemesanan;
  String? created_at;
  String? updated_at;

  RestockData({
    this.id,
    this.nama_product,
    this.id_product,
    this.store_id,
    this.purchase_id,
    this.size,
    this.qty,
    this.harga,
    this.status,
    this.tanggal_pemesanan,
    this.created_at,
    this.updated_at,
  });
  RestockData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    nama_product = json['nama_product']?.toString();
    id_product = json['id_product']?.toInt();
    store_id = json['store_id']?.toInt();
    purchase_id = json['purchase_id']?.toInt();
    size = json['size']?.toString();
    qty = json['qty']?.toInt();
    harga = json['harga']?.toInt();
    status = json['status']?.toString();
    tanggal_pemesanan = json['tanggal_pemesanan']?.toString();
    created_at = json['created_at']?.toString();
    updated_at = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['nama_product'] = nama_product;
    data['id_product'] = id_product;
    data['store_id'] = store_id;
    data['purchase_id'] = purchase_id;
    data['size'] = size;
    data['qty'] = qty;
    data['harga'] = harga;
    data['status'] = status;
    data['tanggal_pemesanan'] = tanggal_pemesanan;
    data['created_at'] = created_at;
    data['updated_at'] = updated_at;
    return data;
  }
}

class Restock {
/*
{
  "success": true,
  "data": [
    {
      "id": 9,
      "nama_product": "Adidas New Version",
      "id_product": 69,
      "store_id": 5,
      "purchase_id": 12,
      "size": "40",
      "qty": 30,
      "harga": 2500000,
      "status": "dikirim",
      "tanggal_pemesanan": "11-10-2023",
      "created_at": "2023-11-10T09:50:41.000000Z",
      "updated_at": "2023-11-10T09:50:41.000000Z"
    }
  ],
  "message": "Products retrieved successfully."
} 
*/

  bool? success;
  List<RestockData?>? data;
  String? message;

  Restock({
    this.success,
    this.data,
    this.message,
  });
  Restock.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <RestockData>[];
      v.forEach((v) {
        arr0.add(RestockData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
