///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class UangKeluarModelData {
/*
{
  "id": 89,
  "nominal": 2000000,
  "tanggal_pengeluaran": "11-10-2023",
  "note": "restock",
  "store_id": 5,
  "total": 20000000,
  "qty": 30,
  "created_at": "2023-11-21T03:34:44.000000Z",
  "updated_at": "2023-11-21T03:34:44.000000Z",
  "nama_admin": "admin11",
  "nama_product": "adidas"
} 
*/

  int? id;
  int? nominal;
  String? tanggal_pengeluaran;
  String? note;
  int? store_id;
  int? total;
  int? qty;
  String? created_at;
  String? updated_at;
  String? nama_admin;
  String? nama_product;

  UangKeluarModelData({
    this.id,
    this.nominal,
    this.tanggal_pengeluaran,
    this.note,
    this.store_id,
    this.total,
    this.qty,
    this.created_at,
    this.updated_at,
    this.nama_admin,
    this.nama_product,
  });
  UangKeluarModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    nominal = json['nominal']?.toInt();
    tanggal_pengeluaran = json['tanggal_pengeluaran']?.toString();
    note = json['note']?.toString();
    store_id = json['store_id']?.toInt();
    total = json['total']?.toInt();
    qty = json['qty']?.toInt();
    created_at = json['created_at']?.toString();
    updated_at = json['updated_at']?.toString();
    nama_admin = json['nama_admin']?.toString();
    nama_product = json['nama_product']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['nominal'] = nominal;
    data['tanggal_pengeluaran'] = tanggal_pengeluaran;
    data['note'] = note;
    data['store_id'] = store_id;
    data['total'] = total;
    data['qty'] = qty;
    data['created_at'] = created_at;
    data['updated_at'] = updated_at;
    data['nama_admin'] = nama_admin;
    data['nama_product'] = nama_product;
    return data;
  }
}

class UangKeluarModel {
/*
{
  "success": true,
  "data": [
    {
      "id": 89,
      "nominal": 2000000,
      "tanggal_pengeluaran": "11-10-2023",
      "note": "restock",
      "store_id": 5,
      "total": 20000000,
      "qty": 30,
      "created_at": "2023-11-21T03:34:44.000000Z",
      "updated_at": "2023-11-21T03:34:44.000000Z",
      "nama_admin": "admin11",
      "nama_product": "adidas"
    }
  ],
  "message": "Products retrieved successfully."
} 
*/

  bool? success;
  List<UangKeluarModelData?>? data;
  String? message;

  UangKeluarModel({
    this.success,
    this.data,
    this.message,
  });
  UangKeluarModel.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <UangKeluarModelData>[];
      v.forEach((v) {
        arr0.add(UangKeluarModelData.fromJson(v));
      });
      this.data = arr0;
    }
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    data['message'] = message;
    return data;
  }
}
